
[env:esp32-s2-kaluga-1]
platform = espressif32
board = esp32-s2-kaluga-1
framework = arduino
lib_deps =
    spacehuhn/SimpleCLI@^1.1.4
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer
build_flags =
    -D USB_CUSTOM_DESCRIPTORS
    -I custom_usb_descriptors
    -D USB_PID=0x0002
    -D USB_VID=0x303a
    -D USB_MANUFACTURER='"Espressif Systems"'
lib_extra_dirs = custom_usb_descriptors

[env:adafruit_qtpy_esp32s3]
platform = espressif32 @ ^6.3.2
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200
#upload_port = /dev/tty.usbmodem11101
lib_deps =
    spacehuhn/SimpleCLI@^1.1.4
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer
    https://github.com/adafruit/Adafruit_NeoPixel.git
    ; -D USB_CUSTOM_DESCRIPTORS
    ; -I custom_usb_descriptors
    ; -D USB_PID=0x0002
    ; -D USB_VID=0x303a
    ; -D USB_MANUFACTURER='"Espressif Systems"'

lib_extra_dirs = custom_usb_descriptors
board_build.flash_size = 4MB
board_build.partitions =  default.csv
board_build.psram = enabled

[env:lilygo-t-dongle-s3]
platform = espressif32 @ ^6.3.2
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    spacehuhn/SimpleCLI@^1.1.4
    me-no-dev/AsyncTCP@^1.1.1
    me-no-dev/ESPAsyncWebServer
    lovyan03/LovyanGFX@^1.1.16
build_flags =
    -D USB_CUSTOM_DESCRIPTORS
    -I custom_usb_descriptors
    -D USB_PID=0x0002
    -D USB_VID=0x303a
    -D USB_MANUFACTURER='"LilyGo"'
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LILYGO_T_DONGLE_S3
    -D DISPLAY_RST=1
    -D DISPLAY_DC=2
    -D DISPLAY_MOSI=3
    -D DISPLAY_CS=4
    -D DISPLAY_SCLK=5
    -D DISPLAY_LEDA=38
    -D DISPLAY_MISO=-1
    -D DISPLAY_BUSY=-1
    -D DISPLAY_WIDTH=160
    -D DISPLAY_HEIGHT=80
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D DOTSTAR_NUM=1
    -D DOTSTAR_DI=40
    -D DOTSTAR_CI=39
lib_extra_dirs = custom_usb_descriptors
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram = enabled
